name: hiramring
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16289
title: 'Hiram Ring: musician, linguist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080806'
    - '#776037'
    - '#8c8f62'
    - '#d6f7ff'
    - '#d1a99f'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
