name: hiramring
favicon: null
layout_spectrum: 0.18405483406968415
typography_spectrum: 0.75492
title: 'Hiram Ring: musician, linguist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130413'
    - '#b6ae8a'
    - '#777d5f'
    - '#432332'
    - '#c7d1b1'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
