name: hiramring
favicon: null
layout_spectrum: 0.18405483406968415
typography_spectrum: 0.75492
title: 'Hiram Ring: musician, linguist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090907'
    - '#8b8e61'
    - '#765d34'
    - '#d4f6ff'
    - '#d2aaa0'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
